### ISSUE TITLE
Added Configuration to Disable/Enable lambda serverless yml 

### ISSUE THREAD

**Issue by CharanRoot** [Dynatrace/serverless-oneagent#14]
Currently, Dynatrace applying to all lambda in the serverless.yml file.

can we provide config to Disable/Enable Lambda in the serverless.yml?

Thanks.

**Comment by CharanRoot** [comment]
@Hollerberg ^

**Comment by Hollerberg** [comment]
I will look into it. I see one issue with
```
package:
  individually: true
```
@dynatrace/oneagent would be included in the individual zip files even when monitoring has been disabled for one of the functions (but OneAgent will not be injected into the excluded function).

**Comment by Hollerberg** [comment]
I added the option to exclude functions from monitoring to 1.0.14 (published some hours ago). Hope this will work out for you.
```yaml
...
functions:
  lambdaTest1:
    handler: test/first.handler

  lambdaTest2:
    handler: test/second.handler
...
custom:
  serverless-oneagent:
    # enable serverless-oneagent plugin verbose mode
    verbose: true
    # specify @next Dynatrace OneAgent npm module
    npmModuleVersion: next
    exclude:
      - lambdaTest2
```
