### ISSUE TITLE
Recieving this error when deploying:  ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by jordan112** [Dynatrace/serverless-oneagent#20]
when we remove the plugin details, it works fine.  Is adding the **serverless-oneagent** plugin adding too much to take up space?

````
plugins:
    - '@dynatrace/serverless-oneagent'
````
Deploying to AWS Lambda using Node version v10.18

**Comment by jordan112** [comment]
We were able to get past this issue by adding this to the _serverless.yml_ file

````
package:
  individually: true
  exclude:
  - tmp/**
  - .git/**
````
