### ISSUE TITLE
error Couldn't find any versions for "@dynatrace/oneagent" that matches "*"

### ISSUE THREAD

**Issue by mcsmcs** [Dynatrace/serverless-oneagent#4]
When trying to deploy via serverless (`sls deploy`) it looks like the plugin tries to install `@dynatrace/oneagent` based on what I provide in `npmModuleVersion`.

This error comes up when `npmModuleVersion` is undefined, when I define it as `next`, or an actual version number.

Running `sls webpack` does not result in the same error - it _appears_ to package fine.

**Comment by Hollerberg** [comment]
I could not reproduce the issue. Could you post the (relevant parts) of the serverless.yml, command line logs (please run sls --verbose deploy)?

**Comment by mcsmcs** [comment]
Abridged version of serverless.yml & output of `ENV=dev sls deploy`

```yaml
# serverless.yml
service: products-lambda

# Keep environment specific configurations in separate files
# These need to change to match your environment
custom: ${file(environment/${self:provider.stage}.js)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:ENV,opt:stage,'dev'}
  environment:
    ENV: ${self:provider.stage}

package:
  individually: true
  exclude:
    - ./**
    - '!node_modules/**'
  include:
    - src/**
    - environment/**

functions:
  options:
    handler: src/http-options-handler.handle
    events:
      - http:
          path: v1/{path+}
          method: options
  products:
    handler: src/products-handler.handle
    events:
      - http:
          path: v1/products
          method: get
  productupdates:
    handler: src/products-updates-handler.handle
    events:
      - http:
          path: v1/productupdates/{options}
          method: get
  newproducts:
    handler: src/newproducts-handler.handle
    events:
      - http:
          path: v1/newproducts
          method: get

resources:
  Resources:

plugins:
  - serverless-domain-manager
  - serverless-log-forwarding
  - serverless-plugin-aws-alerts
  - serverless-webpack
  - '@dynatrace/serverless-oneagent'
```

```javascript
// this is the configuration for 'custom'
module.exports = {
  reponame: "products",
  webpack: {
    includeModules: "true",
    packager: "yarn",
  },
  "serverless-oneagent": {
    npmModuleVersion: '1.157.186-1.0.0',  // same result when this isn't defined
    options: "${ssm:/path/to/dynatrace/DT_LAMBDA_OPTIONS~true}",
  },
};
```

```
 /node-serverless$ ENV=dev sls deploy
Serverless: Updating Log Forwarding Resources...
Serverless: Log Forwarding Resources Updated
Serverless: WARNING: More than one matching handlers found for 'src/http-options-handler'. Using 'src/http-options-handler.js'.
Serverless: WARNING: More than one matching handlers found for 'src/products-handler'. Using 'src/products-handler.js'.
Serverless: WARNING: More than one matching handlers found for 'src/products-updates-handler'. Using 'src/products-updates-handler.js'.
Serverless: WARNING: More than one matching handlers found for 'src/newproducts-handler'. Using 'src/newproducts-handler.js'.
Serverless: Bundling with Webpack...
Time: 984ms
                      Asset     Size  Chunks             Chunk Names
src/http-options-handler.js  3.14 kB       0  [emitted]  src/http-options-handler
Time: 1230ms
                  Asset     Size  Chunks             Chunk Names
src/products-handler.js  25.4 kB       0  [emitted]  src/products-handler
Time: 1229ms
                          Asset     Size  Chunks             Chunk Names
src/products-updates-handler.js  25.7 kB       0  [emitted]  src/products-updates-handler
Time: 1229ms
                     Asset     Size  Chunks             Chunk Names
src/newproducts-handler.js  25.4 kB       0  [emitted]  src/newproducts-handler
    + 4 hidden modules

Serverless: WARNING: Could not determine version of module @dynatrace/oneagent
Serverless: WARNING: Could not determine version of module @dynatrace/oneagent
Serverless: WARNING: Could not determine version of module @dynatrace/oneagent
Serverless: WARNING: Could not determine version of module @dynatrace/oneagent
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: @dynatrace/oneagent, moment@^2.20.1

  Error --------------------------------------------------

  yarn install --frozen-lockfile --non-interactive failed with code 1

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.32.0
```
